### PR TITLE
Some docs work

### PR DESCRIPTION
**Pull request by Pike**
I have a few ideas on how to clean up and improve the docs tooling.

### CODE REVIEW

**Comment by Pike** [comment]
So one of the things I'd like to get to is versioned docs (like on rtd). That requires a healthy amount of actual code, which isn't great to put into the `build-docs` script.

I'm leaning towards refactoring the code into `fluent.docs`. Cons: It feels like people using Fluent would be interested in it. Pros: It's a unique name for the python tooling around the docs. And I haven't come up with a better place.

@zbraniecki , any opinions and/or suggestions? @stasm ?

Side note: the current state of this branch is already a good improvement, I chopped a bit of dead wood, and there's automation to publish the docs. I wouldn't want to merge this before the `github-pages-deploy-action` has its v4 release, but that should come soon. The current state of the PR points to an in-development branch.

**Comment by Pike** [comment]
I'm going with `fluent.docs` for now, mostly because I have cycles to spare. In the end, this is probably easy to move/rename as a whole.

**Comment by Pike** [comment]
Hi @zbraniecki , this is ready for review now. The generated docs are up on https://pike.github.io/python-fluent/fluent.runtime/stable/ etc for you to also have access to how this renders.

There's a few visual fixes that come with the updated sphinx and pygments versions, and the version picker, of course.

**Review by zbraniecki — APPROVED** [review]
lgtm

**Comment by Pike** [comment]
Merged, and docs deployed themselves gracefully.

**Pull request merged**
