### PR TITLE
Drop Python 2.7, 3.5 support, add 3.6-3.9 for fluent.syntax

### PR DESCRIPTION
**Pull request by Pike**
This is pretty mechanic, doing Syntax first, as fluent.runtime and fluent.pygments depend on released versions of fluent.syntax.

* Update metadata and testing matrix
* Drop six
* pyupgrade --py36-plus
* Version bump and release notes

pyupgrade comes from https://github.com/asottile/pyupgrade.

I did try `--py39-plus` just for the kicks of it, and that didn't show anything more.

### CODE REVIEW

**Comment by Pike** [comment]
@zbraniecki , this looks good for review to me now. r?

First phase of #162, not adding any closing keywords on this one.

**Review by zbraniecki — APPROVED** [review]
lgtm!

**Comment by Pike** [comment]
Thanks for the review.
I have no permissions on this repo, can you merge this?

**Comment by zbraniecki** [comment]
> I have no permissions on this repo

That's fixed now.

**Pull request merged**
